version: "3.8"

services:
  django:
    container_name: api
    build:
      context: ./api
    env_file:
      - ./api/.env
    ports:
      - 8000:8000
    volumes:
      - ./api:/api
    depends_on:
      - psql

  psql:
    container_name: db
    image: "postgres:14.1-alpine"
    environment:
      - POSTGRES_DB=todo_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password

  react:
    container_name: ui
    build:
      context: ./ui
    ports:
      - 3000:3000
    volumes:
      - ./ui/src:/ui/src
