apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: todo-app
  labels:
    app: postgres
data:
  POSTGRES_DB: tododb
  POSTGRES_USER: admin
  POSTGRES_PORT: "5432"
  POSTGRES_HOST: postgres-service

  DJANGO_SUPERUSER_EMAIL: 'admin@admin.com'
  DJANGO_SUPERUSER_USERNAME: 'admin'
  DJANGO_SUPERUSER_PASSWORD: 'password'