apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api-deployment
  # namespace: todo-app
  labels:
    app: todo-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo-api
  template:
    metadata:
      labels:
        app: todo-api
    spec:
      containers:
      - name: todo-api-container
        image: localhost:32000/todo-api:latest
        ports:
        - containerPort: 8000
        envFrom:
          - configMapRef:
              name: postgres-config
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_PASSWORD
      hostAliases:
      - hostnames:
        - "postgres-service"
        ip: "192.168.64.6"