version: "3.8"

services:
  django:
    container_name: api
    build:
      context: ./api
    env_file:
      - ./api/.env
    ports:
      - 8000:8000
    volumes:
      - ./api:/api
    depends_on:
      - psql

  psql:
    container_name: db
    image: "postgres:14.1-alpine"
    environment:
      - POSTGRES_DB=todo_db
      - POSTGRES_USER=postgresadmin
      - POSTGRES_PASSWORD=password
    volumes:
      - todo_postgres_data:/var/lib/postgresql/data

  react:
    container_name: ui
    build:
      context: ./ui
    ports:
      - 8091:80
    volumes:
      - ./ui/src:/ui/src

volumes:
  todo_postgres_data: