apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.api.name }}-deployment
  labels:
    app: {{ .Values.app }}
    group: {{ .Values.group }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.api.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.api.name }}
    spec:
      containers:
        - name: {{ .Values.api.name }}-container
          image: "{{ .Values.api.container.image.repository }}:{{ .Chart.AppVersion }}"
          ports:
            - containerPort: {{ .Values.api.container.port }}
          command: ["sh", "-c", "sleep 10; pipenv run python manage.py migrate && pipenv run python manage.py runserver 0.0.0.0:8000"]
          envFrom:
            - configMapRef:
                name: {{ .Values.api.config.name }}
          env:
          {{- $secretName := .Values.api.secret.name }}
          {{- range .Values.api.secret.data }}
            - name: {{ .key }}
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: {{ .key }}
          {{- end}}