apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.api.name }}-job
  labels:
    app: {{ .Values.app }}
    group: {{ .Values.group }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      containers:
      - name: {{ .Values.api.name }}-job-container
        image: "{{ .Values.api.container.image.repository }}:{{ .Chart.AppVersion }}"
        command: ["sh", "-c", "sleep 10 && chmod o+x entrypoint.sh && ./entrypoint.sh"]
        # lifecycle:
        #   postStart:
        #     exec:
        #       command: ["sh", "-c", "sleep 10 && chmod o+x entrypoint.sh && ./entrypoint.sh"]
        envFrom:
          - configMapRef:
              name: {{ .Values.api.config.name }}
        env:
        {{- $secretName := .Values.api.secret.name }}
        {{- range .Values.api.secret.data }}
          - name: {{ .key }}
            valueFrom:
              secretKeyRef:
                name: {{ $secretName }}
                key: {{ .key }}
        {{- end}}        
      restartPolicy: Never
  backoffLimit: 4
