apiVersion: apps/v1
kind: Deployment
metadata:
name: inventory-api-deployment labels:
    app: todo-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo-api
  template:
    metadata:
      labels:
        app: todo-api
    spec:
      containers:
      - name: todo-api-container
        image: localhost:32000/inventory-api:v1
        ports:
        - containerPort: 8000