apiVersion: v1
kind: {{ .Values.postgres.storage.pv.kind }}
metadata:
  name: {{ .Values.postgres.storage.pv.name }}
  labels:
    app: {{ .Values.app }}
    group: {{ .Values.group }}
spec:
  storageClassName: {{ .Values.postgres.storage.pv.storageClassName }}
  accessModes:
    - {{ .Values.postgres.storage.pv.accessMode }}
  capacity:
      storage: {{ .Values.postgres.storage.pv.capacity }}
  hostPath:
    path: {{ .Values.postgres.storage.pv.hostPath | quote }}