kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: todo-db-network
  namespace: todo-app
spec:
  podSelector:
    matchLabels:
      app: postgres
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: todo-api
      ports:
      - port: 5432