kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: todo-ui-network
  namespace: todo-app
spec:
  podSelector:
    matchLabels:
      app: todo-ui
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: todo-api
      ports:
      - port: 8000