###########################
# Job
###########################
apiVersion: batch/v1
kind: Job
metadata:
  name: django-job
spec:
  template:
    spec:
      containers:
      - name: django-job-container
        image: localhost:32000/api:latest
        command: ["sh", "-c", "/entrypoint.sh"]
        envFrom:
        - configMapRef:
            name: app-config    
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: POSTGRES_PASSWORD
          - name: DJANGO_SUPERUSER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: DJANGO_SUPERUSER_PASSWORD
      restartPolicy: Never
  backoffLimit: 4
