apiVersion: batch/v1
kind: Job
metadata:
  name: api-job
  namespace: todo-app
  labels:
    app: todo-api
spec:
  template:
    spec:
      containers:
      - name: todo-api-job-container
        image: localhost:32000/todo-api:latest
        command: ["sh", "-c", "sleep 10 && chmod o+x entrypoint.sh && ./entrypoint.sh"]
        envFrom:
          - configMapRef:
              name: api-config
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_PASSWORD
      restartPolicy: Never
  backoffLimit: 4
