apiVersion: v2
name: todo-app-chart
description: A Helm chart for Kubernetes

type: application
version: 0.1.0
appVersion: "latest"

dependencies:
  - name: todoDB
    condition: enabled
  - name: todoAPI
    condition: enabled
  - name: todoUI
    condition: enabled